[package]
name = "verify_sent_tx_prep"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.1.0", features = ["full"] }
alloy-rlp = "0.1.0"
alloy-trie = "0.1.0"
tokio = { version = "1.0", features = ["full"] }
hex = "0.4.3"
serde_json = "1.0"
